import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/Components/Shared/Navbar";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const plusSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html
      lang="en"
      className={cn("h-full", "antialiased", "dark", plusSans.className, "font-sans", geist.variable)}
    >
     
      <body className="min-h-full flex flex-col bg-zinc-950 text-zinc-50 select-none">
        <Navbar />
        <main className="grow">
          {children}
        </main>
      </body>
    </html>
  );
}