import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

import Navbar from "@/Components/Shared/Navbar";
import { ThemeProvider } from "@/Components/providers/ThemeProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

const plusSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CITYFIX",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning   
      className={cn("h-full antialiased", plusSans.className)}
      
    >
      <body className="min-h-full flex flex-col bg-white text-slate-900 dark:bg-zinc-950 dark:text-slate-50 transition-colors duration-300">
       
        <ThemeProvider>
          <Navbar />
          <main className="grow">
            {children}
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}