import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

import Navbar from "@/Components/Shared/Navbar";
import { ThemeProvider } from "@/Components/providers/ThemeProvider";
import { cn } from "@/lib/utils";

const plusSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CITYFIX",
  description: "Generated by create next app",
};

/**
 * RootLayout
 * ──────────
 * Key fixes for the global dark/light mode issue:
 *
 * 1. REMOVED `data-theme='light'` from <html> — that attribute is for
 *    DaisyUI. Tailwind v4 dark mode works via the `dark` CLASS, not
 *    data-theme. Having it hardcoded blocked next-themes from switching.
 *
 * 2. REMOVED the hardcoded `light` class from <html>. next-themes will
 *    now manage that class (adding/removing `dark`) dynamically.
 *
 * 3. Added `suppressHydrationWarning` on <html>. next-themes injects a
 *    blocking script that sets the class before React hydrates. Without
 *    this attribute, React throws a hydration mismatch warning for the
 *    class attribute difference between server and client.
 *
 * 4. Wrapped the entire tree in <ThemeProvider>. It must be INSIDE
 *    <body> (or wrapping it) but NOT around <html> itself — the html
 *    element is managed by React, not the provider.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning   // ← required by next-themes; suppresses class mismatch warning
      className={cn("h-full antialiased", plusSans.className)}
      // ✅ NO `data-theme` here — that's DaisyUI syntax and conflicts with Tailwind's class-based dark mode
      // ✅ NO hardcoded `light` class — next-themes will add/remove `dark` automatically
    >
      <body className="min-h-full flex flex-col bg-white text-slate-900 dark:bg-zinc-950 dark:text-slate-50 transition-colors duration-300">
        {/*
          ThemeProvider must be inside <body> as a Client boundary.
          It cannot wrap <html> because <html> is a Server Component boundary.
        */}
        <ThemeProvider>
          <Navbar />
          <main className="grow">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}